FROM centos:7

LABEL maintainer="Paulo Kinjo <paulokinjo@hotmail.com>"
LABEL description="Configure a centos image with ansible"

RUN yum install epel-release -y
RUN yum install ansible -y

ENTRYPOINT ["/bin/bash"]
