---
- hosts: loadbalancer
  tasks:
    - service:
        name: nginx
        state: stopped

- hosts: webserver
  become: true
  tasks:
    - service:
        name: apache2
        state: stopped

- hosts: database
  become: yes
  tasks:
    - service:
        name: mysql
        state: restarted

- hosts: webserver
  become: yes
  tasks:
    - service:
        name: apache2
        state: started

- hosts: loadbalancer
  become: yes
  tasks:
    - service:
        name: nginx
        state: started
