Vagrant.configure("2") do |config|
  config.vm.define "lampstack" do |lampstack|
    lampstack.vm.box = "ubuntu/trusty64"
    lampstack.vm.hostname = "lampstack"
    lampstack.vm.network "private_network", ip: "192.168.34.10"
  end
end