# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

    config.vm.define "acs" do |acs|
      acs.vm.box = "ubuntu/trusty64"
      acs.vm.hostname = "acs"
      acs.vm.network "private_network", ip: "192.168.33.10"
    end
  
    config.vm.define "app1" do |app1|
      app1.vm.box = "ubuntu/trusty64"
      app1.vm.hostname = "app1"
      app1.vm.network "private_network", ip: "192.168.33.20"      
    end

    config.vm.define "app2" do |app2|
      app2.vm.box = "ubuntu/trusty64"
      app2.vm.hostname = "app2"
      app2.vm.network "private_network", ip: "192.168.33.30"      
    end
  
    config.vm.define "lb" do |lb|
      lb.vm.box = "ubuntu/trusty64"
      lb.vm.hostname = "lb"
      lb.vm.network "private_network", ip: "192.168.33.40"
    end

    config.vm.define "db" do |db|
      db.vm.box = "ubuntu/trusty64"
      db.vm.hostname = "db"
      db.vm.network "private_network", ip: "192.168.33.50"
    end
  
  end
  